# Generated by Django 5.2.12 on 2026-04-28 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('grade', models.IntegerField(db_column='цифра', verbose_name='Цифра класса')),
                ('letter', models.CharField(db_column='буква', max_length=1, verbose_name='Буква класса')),
                ('academic_year', models.CharField(blank=True, db_column='учебный_год', max_length=9, null=True, verbose_name='Учебный год')),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классы',
                'db_table': 'класс',
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(db_column='фамилия', max_length=45, verbose_name='Фамилия')),
                ('first_name', models.CharField(db_column='имя', max_length=45, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, db_column='отчество', max_length=45, null=True, verbose_name='Отчество')),
                ('login', models.CharField(db_column='логин', max_length=55, unique=True, verbose_name='Логин')),
                ('password_hash', models.CharField(db_column='пароль_хеш', max_length=256, verbose_name='Пароль (хеш)')),
                ('phone', models.CharField(blank=True, db_column='телефон', max_length=15, null=True, verbose_name='Телефон')),
                ('email', models.CharField(blank=True, db_column='электронная_почта', max_length=100, null=True, verbose_name='Электронная почта')),
            ],
            options={
                'verbose_name': 'Родитель',
                'verbose_name_plural': 'Родители',
                'db_table': 'родитель',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(db_column='номер', max_length=10, unique=True, verbose_name='Номер кабинета')),
                ('floor', models.IntegerField(blank=True, db_column='этаж', null=True, verbose_name='Этаж')),
                ('capacity', models.IntegerField(blank=True, db_column='вместимость', null=True, verbose_name='Вместимость')),
                ('description', models.CharField(blank=True, db_column='описание', max_length=255, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Кабинет',
                'verbose_name_plural': 'Кабинеты',
                'db_table': 'кабинет',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='название', max_length=100, verbose_name='Название')),
                ('description', models.CharField(blank=True, db_column='описание', max_length=255, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
                'db_table': 'предмет',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField(db_column='день_недели', verbose_name='День недели (1-пн, 2-вт...)')),
                ('lesson_number', models.IntegerField(db_column='номер_урока', verbose_name='Номер урока')),
                ('start_time', models.TimeField(blank=True, db_column='время_начала', null=True, verbose_name='Время начала')),
                ('end_time', models.TimeField(blank=True, db_column='время_конца', null=True, verbose_name='Время конца')),
                ('class_id', models.ForeignKey(db_column='класс_id', on_delete=django.db.models.deletion.CASCADE, to='journal.class', verbose_name='Класс')),
                ('room', models.ForeignKey(db_column='кабинет_id', on_delete=django.db.models.deletion.CASCADE, to='journal.room', verbose_name='Кабинет')),
                ('subject', models.ForeignKey(db_column='предмет_id', on_delete=django.db.models.deletion.CASCADE, to='journal.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Урок в расписании',
                'verbose_name_plural': 'Расписание',
                'db_table': 'расписание',
            },
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(db_column='описание_задания', max_length=255, verbose_name='Описание задания')),
                ('schedule', models.ForeignKey(db_column='расписание_id', on_delete=django.db.models.deletion.CASCADE, to='journal.schedule', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Домашнее задание',
                'verbose_name_plural': 'Домашние задания',
                'db_table': 'домашнее_задание',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_column='имя', max_length=45, verbose_name='Имя')),
                ('last_name', models.CharField(db_column='фамилия', max_length=45, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, db_column='отчество', max_length=45, null=True, verbose_name='Отчество')),
                ('birth_date', models.DateField(blank=True, db_column='дата_рождения', null=True, verbose_name='Дата рождения')),
                ('login', models.CharField(db_column='логин', max_length=55, unique=True, verbose_name='Логин')),
                ('password_hash', models.CharField(db_column='пароль_хеш', max_length=256, verbose_name='Пароль (хеш)')),
                ('class_id', models.ForeignKey(db_column='класс_id', on_delete=django.db.models.deletion.CASCADE, to='journal.class', verbose_name='Класс')),
            ],
            options={
                'verbose_name': 'Ученик',
                'verbose_name_plural': 'Ученики',
                'db_table': 'ученик',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('grade', models.IntegerField(blank=True, db_column='оценка', null=True, verbose_name='Оценка')),
                ('grade_date', models.DateField(db_column='дата_оценки', verbose_name='Дата оценки')),
                ('schedule', models.ForeignKey(db_column='расписание_id', on_delete=django.db.models.deletion.CASCADE, to='journal.schedule', verbose_name='Урок')),
                ('student', models.ForeignKey(db_column='ученик_id', on_delete=django.db.models.deletion.CASCADE, to='journal.student', verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценки',
                'db_table': 'оценка',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_column='имя', max_length=45, verbose_name='Имя')),
                ('last_name', models.CharField(db_column='фамилия', max_length=45, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, db_column='отчество', max_length=45, null=True, verbose_name='Отчество')),
                ('email', models.CharField(blank=True, db_column='электронная_почта', max_length=100, null=True, verbose_name='Электронная почта')),
                ('phone', models.CharField(blank=True, db_column='телефон', max_length=15, null=True, verbose_name='Телефон')),
                ('login', models.CharField(db_column='логин', max_length=55, unique=True, verbose_name='Логин')),
                ('password_hash', models.CharField(db_column='пароль_хеш', max_length=256, verbose_name='Пароль (хеш)')),
                ('homeroom_class', models.ForeignKey(blank=True, db_column='классный_руководитель_класса_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='journal.class', verbose_name='Класс, в котором учитель является классным руководителем')),
            ],
            options={
                'verbose_name': 'Учитель',
                'verbose_name_plural': 'Учителя',
                'db_table': 'учитель',
            },
        ),
        migrations.AddField(
            model_name='schedule',
            name='teacher',
            field=models.ForeignKey(db_column='учитель_id', on_delete=django.db.models.deletion.CASCADE, to='journal.teacher', verbose_name='Учитель'),
        ),
        migrations.CreateModel(
            name='ParentStudent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('parent', models.ForeignKey(db_column='родитель_id', on_delete=django.db.models.deletion.CASCADE, to='journal.parent', verbose_name='Родитель')),
                ('student', models.ForeignKey(db_column='ученик_id', on_delete=django.db.models.deletion.CASCADE, to='journal.student', verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Связь родителя и ученика',
                'verbose_name_plural': 'Связи родителей и учеников',
                'db_table': 'родитель_ученик',
                'unique_together': {('parent', 'student')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('class_id', 'day_of_week', 'lesson_number')},
        ),
        migrations.CreateModel(
            name='TeacherSubject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.ForeignKey(db_column='предмет_id', on_delete=django.db.models.deletion.CASCADE, to='journal.subject', verbose_name='Предмет')),
                ('teacher', models.ForeignKey(db_column='учитель_id', on_delete=django.db.models.deletion.CASCADE, to='journal.teacher', verbose_name='Учитель')),
            ],
            options={
                'verbose_name': 'Связь учителя и предмета',
                'verbose_name_plural': 'Связи учителей и предметов',
                'db_table': 'учитель_предмет',
                'unique_together': {('teacher', 'subject')},
            },
        ),
    ]
