# Generated by Django 6.0.3 on 2026-04-28 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='parent',
            table='родители',
        ),
    ]
