# Generated by Django 5.2.12 on 2026-05-19 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_alter_parent_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='homework/%Y/%m/%d/', verbose_name='Файл'),
        ),
        migrations.AlterModelTable(
            name='parent',
            table='родители',
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='заголовок', max_length=255, verbose_name='Заголовок')),
                ('text', models.TextField(db_column='текст', verbose_name='Текст объявления')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='дата_создания', verbose_name='Дата создания')),
                ('class_id', models.ForeignKey(db_column='класс_id', on_delete=django.db.models.deletion.CASCADE, to='journal.class', verbose_name='Класс')),
                ('teacher', models.ForeignKey(db_column='учитель_id', on_delete=django.db.models.deletion.CASCADE, to='journal.teacher', verbose_name='Учитель')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'db_table': 'объявления',
            },
        ),
    ]
