# Generated by Django 5.2.12 on 2026-05-19 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_homework_file_alter_parent_table_announcement'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='parent',
            table='родитель',
        ),
    ]
