# Generated by Django 5.2.12 on 2026-05-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_alter_parent_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='file',
            field=models.FileField(blank=True, db_column='файл', null=True, upload_to='homework/%Y/%m/%d/', verbose_name='Файл'),
        ),
    ]
